# 1. Define who can assume/use this IAM Role (e.g., the Lambda service)
data "aws_iam_policy_document" "assume_role_sharing" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["://amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "this" {
  name               = var.role_name
  assume_role_policy = data.aws_iam_policy_document.assume_role_sharing.json
}

# 2. Define WHAT this role is allowed to do (Read/Write to your specific S3 bucket)
data "aws_iam_policy_document" "s3_access" {
  statement {
    actions   = ["s3:GetObject", "s3:PutObject", "s3:ListBucket"]
    resources = [
      var.target_s3_bucket_arn,
      "${var.target_s3_bucket_arn}/*"
    ]
  }
}

resource "aws_iam_policy" "this" {
  name        = "${var.role_name}-s3-policy"
  description = "Dynamic policy generated by module for S3 access"
  policy      = data.aws_iam_policy_document.s3_access.json
}

# 3. Attach the policy directly to the role
resource "aws_iam_role_policy_attachment" "this" {
  role       = aws_iam_role.this.name
  policy_arn = aws_iam_policy.this.arn
}